import { 
  WorkflowApproval, 
  ApprovalFeedback, 
  MaintenanceRequest, 
  BillItem, 
  RentPayment, 
  LeaseAgreement, 
  ProductivityMetric,
  TenantComplaint,
  TroubleshootingSession
} from '../types';

export const INITIAL_LEASES: LeaseAgreement[] = [
  {
    id: 'lease-101',
    propertyName: 'Highland Park Residences',
    unitNumber: '4B',
    tenantName: 'Elena Rostova',
    tenantEmail: 'elena.rostova@example.com',
    tenantId: 'user-tenant-1',
    monthlyRent: 2850,
    securityDeposit: 2850,
    startDate: '2026-06-01',
    endDate: '2027-05-31',
    status: 'active',
    termsAccepted: true,
    signatureData: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',
    signedAt: '2026-05-28T14:32:00Z',
    signatureIp: '198.51.100.44',
    terms: [
      'Tenant agrees to pay monthly rent of $2,850 on or before the 1st calendar day of each month.',
      'Late fee of $150 applies after the 5th day of the month.',
      'Quiet hours observed between 10:00 PM and 7:00 AM daily.',
      'Tenant responsible for minor plumbing stoppages caused by misuse.',
      'Subletting without written prior consent from property manager is strictly prohibited.'
    ],
    createdBy: 'Ariel Agor',
    createdAt: '2026-05-20T10:00:00Z',
    updatedAt: '2026-05-28T14:32:00Z',
  },
  {
    id: 'lease-102',
    propertyName: 'Highland Park Residences',
    unitNumber: '2A',
    tenantName: 'Marcus Vance',
    tenantEmail: 'marcus.v@example.com',
    tenantId: 'user-tenant-2',
    monthlyRent: 3100,
    securityDeposit: 3100,
    startDate: '2026-11-01',
    endDate: '2027-10-31',
    status: 'pending_signature',
    termsAccepted: false,
    terms: [
      'Monthly lease rate of $3,100 payable via automated ACH or tenant portal.',
      'Includes one reserved subterranean parking space (#14).',
      'No alterations or structural painting without landlord written consent.',
      'Tenant agrees to carry active renter insurance with minimum $100k liability.'
    ],
    createdBy: 'Ariel Agor',
    createdAt: '2026-10-01T09:15:00Z',
    updatedAt: '2026-10-01T09:15:00Z',
  },
  {
    id: 'lease-103',
    propertyName: 'Metro Grand Tower',
    unitNumber: '1205',
    tenantName: 'Sophia Chen',
    tenantEmail: 'sophia.chen@example.com',
    monthlyRent: 4200,
    securityDeposit: 4200,
    startDate: '2026-01-15',
    endDate: '2027-01-14',
    status: 'active',
    termsAccepted: true,
    signatureData: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',
    signedAt: '2026-01-10T11:20:00Z',
    signatureIp: '203.0.113.19',
    terms: [
      'Commercial mixed-use residential occupancy lease agreement.',
      'Concierge service included in monthly rent.',
      'HVAC maintenance covered by building engineering team.'
    ],
    createdBy: 'Ariel Agor',
    createdAt: '2026-01-05T16:00:00Z',
    updatedAt: '2026-01-10T11:20:00Z',
  }
];

export const INITIAL_APPROVALS: WorkflowApproval[] = [
  {
    id: 'appr-301',
    title: 'Emergency Main Boiler Valve Replacement (Unit 4B & Riser)',
    type: 'maintenance_expense',
    department: 'maintenance',
    amount: 3450,
    requestedBy: 'user-tech-1',
    requestedByName: 'Devon Miller (Vendor Coordinator)',
    targetEntityId: 'maint-201',
    currentStage: 'Finance Sign-off',
    requiredRoles: ['property_manager', 'finance_officer'],
    status: 'pending',
    bottleneckHours: 14.5,
    priority: 'urgent',
    description: 'High-pressure valve rupture in building C heating riser. Immediate parts order and overtime labor quote submitted by Apex Mechanical LLC.',
    createdAt: '2026-10-02T05:30:00Z',
    updatedAt: '2026-10-02T18:00:00Z',
    commentsCount: 3,
  },
  {
    id: 'appr-302',
    title: 'Commercial Lease Renewal - Unit 2A (Marcus Vance)',
    type: 'lease_agreement',
    department: 'leasing',
    amount: 37200,
    requestedBy: 'user-pm-1',
    requestedByName: 'Ariel Agor (Property Manager)',
    targetEntityId: 'lease-102',
    currentStage: 'Legal / Compliance Review',
    requiredRoles: ['legal_admin', 'executive'],
    status: 'changes_requested',
    bottleneckHours: 32.0,
    priority: 'high',
    description: 'Special concession clause requested: 1 month free on 13-month renewal term. Requires verification of building rent roll debt-service coverage ratio (DSCR).',
    createdAt: '2026-09-30T10:00:00Z',
    updatedAt: '2026-10-01T15:20:00Z',
    commentsCount: 4,
  },
  {
    id: 'appr-303',
    title: 'Vendor Contract: ProClean Landscaping & Snow Removal',
    type: 'vendor_contract',
    department: 'finance',
    amount: 14200,
    requestedBy: 'user-fo-1',
    requestedByName: 'Sarah Jenkins (Finance Officer)',
    currentStage: 'Executive Approval',
    requiredRoles: ['executive'],
    status: 'pending',
    bottleneckHours: 48.2,
    priority: 'medium',
    description: 'Annual winter maintenance service contract renewal for 3 property complexes. Includes $2M general liability rider certificate.',
    createdAt: '2026-09-28T09:00:00Z',
    updatedAt: '2026-10-02T11:00:00Z',
    commentsCount: 2,
  },
  {
    id: 'appr-304',
    title: 'Security Deposit Refund Authorization - Unit 9C (Former Tenant: B. Hayes)',
    type: 'rent_adjustment',
    department: 'leasing',
    amount: 2150,
    requestedBy: 'user-pm-1',
    requestedByName: 'Ariel Agor',
    currentStage: 'Completed Execution',
    requiredRoles: ['property_manager', 'finance_officer'],
    status: 'approved',
    bottleneckHours: 4.1,
    priority: 'low',
    description: 'Move-out inspection cleared with zero deductions. Full deposit wire transfer authorized.',
    createdAt: '2026-09-25T11:00:00Z',
    updatedAt: '2026-09-26T14:30:00Z',
    commentsCount: 1,
  }
];

export const INITIAL_FEEDBACK: ApprovalFeedback[] = [
  {
    id: 'fb-1',
    approvalId: 'appr-301',
    authorId: 'user-fo-1',
    authorName: 'Sarah Jenkins',
    authorRole: 'finance_officer',
    message: 'Can Apex Mechanical break out the overtime surcharge line item? We have a pre-negotiated $120/hr cap under Master Service Agreement #04.',
    type: 'revision_request',
    createdAt: '2026-10-02T08:15:00Z',
  },
  {
    id: 'fb-2',
    approvalId: 'appr-301',
    authorId: 'user-tech-1',
    authorName: 'Devon Miller',
    authorRole: 'vendor_coordinator',
    message: 'Confirmed with Apex Mechanical dispatch. They adjusted the quote down by $380 to honor the master cap. Updated PDF attached in Drive voucher.',
    type: 'comment',
    createdAt: '2026-10-02T10:45:00Z',
  },
  {
    id: 'fb-3',
    approvalId: 'appr-301',
    authorId: 'user-pm-1',
    authorName: 'Ariel Agor',
    authorRole: 'property_manager',
    message: 'Given water risk to Unit 3B ceiling below, emergency waiver granted. Ready for final payment sign-off.',
    type: 'waiver',
    createdAt: '2026-10-02T11:30:00Z',
  },
  {
    id: 'fb-4',
    approvalId: 'appr-302',
    authorId: 'user-legal-1',
    authorName: 'David Stern, Esq.',
    authorRole: 'legal_admin',
    message: 'Clause 14.b does not specify whether the concession applies to the 1st or 13th month. Ambiguity could create dispute upon early termination.',
    type: 'revision_request',
    createdAt: '2026-10-01T14:00:00Z',
  }
];

export const INITIAL_MAINTENANCE: MaintenanceRequest[] = [
  {
    id: 'maint-201',
    title: 'Severe Water Leak Under Kitchen Sink & Riser Valve',
    description: 'Hot water valve is hissing and spraying onto the cabinet backing. Water is accumulating on floor tiles.',
    propertyName: 'Highland Park Residences',
    unitNumber: '4B',
    lesseeId: 'user-tenant-1',
    lesseeName: 'Elena Rostova',
    lesseeEmail: 'elena.rostova@example.com',
    category: 'plumbing',
    priority: 'emergency',
    status: 'vendor_dispatched',
    audioTranscript: "Hi, this is Elena in unit 4B. The pipe right under my kitchen sink started spraying water about twenty minutes ago. It's making a loud whistling sound and the floor is getting flooded. Please send someone right away!",
    aiDamageAnalysis: {
      identifiedIssues: ['Pressurized supply line failure', 'Cabinet water saturation', 'Subfloor moisture risk'],
      severityLevel: 'emergency',
      recommendedTrade: 'plumbing',
      estimatedRepairTime: '1.5 - 2.5 hours',
      suggestedPrecaution: 'Shut off the dual angle-stop valves beneath the sink or the unit main shutoff lever behind the laundry closet.',
    },
    assignedVendor: 'Apex Mechanical & Plumbing Pros',
    vendorContact: '(555) 392-8100',
    vendorETA: '35 mins',
    estimatedCost: 850,
    approvalId: 'appr-301',
    createdAt: '2026-10-02T05:10:00Z',
    updatedAt: '2026-10-02T05:40:00Z',
  },
  {
    id: 'maint-202',
    title: 'HVAC Compressor Short Cycling & Thermostat Blank',
    description: 'Living room temperature has reached 79 degrees. AC unit clicks repeatedly outside on balcony but fan does not spin.',
    propertyName: 'Metro Grand Tower',
    unitNumber: '1205',
    lesseeId: 'user-tenant-3',
    lesseeName: 'Sophia Chen',
    lesseeEmail: 'sophia.chen@example.com',
    category: 'hvac',
    priority: 'high',
    status: 'under_review',
    audioTranscript: "Our air conditioning shut off this afternoon. The Nest thermostat display went totally black, and every few minutes there is a buzzing click from the condenser unit outside.",
    aiDamageAnalysis: {
      identifiedIssues: ['Low voltage transformer blowout or condensate float switch tripped', 'Run capacitor degradation'],
      severityLevel: 'high',
      recommendedTrade: 'hvac',
      estimatedRepairTime: '2 hours',
      suggestedPrecaution: 'Flip HVAC breaker #18 in the utility panel to OFF to prevent compressor coil burn-out.',
    },
    estimatedCost: 420,
    createdAt: '2026-10-02T14:20:00Z',
    updatedAt: '2026-10-02T15:00:00Z',
  },
  {
    id: 'maint-203',
    title: 'Keycard Access Lock Beeping & Intermittent Entry Failure',
    description: 'Unit electronic deadbolt keypad flashes red and requires 4 tries before opening latch.',
    propertyName: 'Highland Park Residences',
    unitNumber: '2A',
    lesseeId: 'user-tenant-2',
    lesseeName: 'Marcus Vance',
    lesseeEmail: 'marcus.v@example.com',
    category: 'electrical',
    priority: 'medium',
    status: 'submitted',
    createdAt: '2026-10-01T19:30:00Z',
    updatedAt: '2026-10-01T19:30:00Z',
  }
];

export const INITIAL_BILLS: BillItem[] = [
  {
    id: 'bill-501',
    billType: 'contractor_invoice',
    vendorName: 'Apex Mechanical & Plumbing Pros',
    invoiceNumber: 'INV-2026-8941',
    amount: 1450.00,
    dueDate: '2026-10-15',
    status: 'approved_for_payment',
    ocrConfidence: 0.98,
    extractedLineItems: [
      { description: 'Emergency Call-out Diagnostic', amount: 150 },
      { description: 'Replace 1.5" Brass Pressure Reducing Valve', amount: 480 },
      { description: 'Plumbing Labor (2 Technicians x 3 hrs)', amount: 720 },
      { description: 'Environmental Disposal & Sealant', amount: 100 }
    ],
    submittedBy: 'Devon Miller',
    paymentMethod: 'ACH Direct Deposit',
    notes: 'Approved under Emergency Authorization #301',
    createdAt: '2026-10-01T11:00:00Z',
    updatedAt: '2026-10-02T09:30:00Z',
  },
  {
    id: 'bill-502',
    billType: 'utility',
    vendorName: 'Consolidated Edison City Water & Power',
    invoiceNumber: 'UTIL-9938210',
    amount: 3240.85,
    dueDate: '2026-10-20',
    status: 'unpaid',
    ocrConfidence: 0.95,
    extractedLineItems: [
      { description: 'Building Common Area Electricity', amount: 1840.20 },
      { description: 'Central Water & Sewer Usage (48,000 Gallons)', amount: 1210.65 },
      { description: 'Municipal Clean Energy Surcharge', amount: 190.00 }
    ],
    submittedBy: 'Sarah Jenkins',
    createdAt: '2026-09-29T16:00:00Z',
    updatedAt: '2026-09-29T16:00:00Z',
  },
  {
    id: 'bill-503',
    billType: 'property_tax',
    vendorName: 'County Assessor Tax Office',
    invoiceNumber: 'TAX-2026-Q3-HP',
    amount: 18500.00,
    dueDate: '2026-10-31',
    status: 'unpaid',
    ocrConfidence: 0.99,
    extractedLineItems: [
      { description: 'Highland Park Parcel 09-112 Real Property Tax Q3', amount: 18500.00 }
    ],
    submittedBy: 'Sarah Jenkins',
    createdAt: '2026-09-15T09:00:00Z',
    updatedAt: '2026-09-15T09:00:00Z',
  },
  {
    id: 'bill-504',
    billType: 'maintenance_receipt',
    vendorName: 'ProClean Commercial Services',
    invoiceNumber: 'PC-8812',
    amount: 980.00,
    dueDate: '2026-09-30',
    status: 'paid',
    ocrConfidence: 0.97,
    paymentMethod: 'Corporate Visa *8821',
    paidAt: '2026-09-28T14:00:00Z',
    submittedBy: 'Ariel Agor',
    createdAt: '2026-09-25T10:00:00Z',
    updatedAt: '2026-09-28T14:00:00Z',
  }
];

export const INITIAL_RENT_PAYMENTS: RentPayment[] = [
  {
    id: 'rent-601',
    leaseId: 'lease-101',
    unitNumber: '4B',
    tenantId: 'user-tenant-1',
    tenantName: 'Elena Rostova',
    amount: 2850,
    period: 'October 2026',
    dueDate: '2026-10-01',
    status: 'paid',
    paidAt: '2026-10-01T08:12:00Z',
    paymentMethod: 'Auto-Pay ACH',
    referenceNumber: 'ACH-88912401',
    createdAt: '2026-09-25T00:00:00Z',
  },
  {
    id: 'rent-602',
    leaseId: 'lease-102',
    unitNumber: '2A',
    tenantId: 'user-tenant-2',
    tenantName: 'Marcus Vance',
    amount: 3100,
    period: 'October 2026',
    dueDate: '2026-10-01',
    status: 'pending',
    referenceNumber: 'INV-RENT-102',
    createdAt: '2026-09-25T00:00:00Z',
  },
  {
    id: 'rent-603',
    leaseId: 'lease-103',
    unitNumber: '1205',
    tenantId: 'user-tenant-3',
    tenantName: 'Sophia Chen',
    amount: 4200,
    period: 'October 2026',
    dueDate: '2026-10-01',
    status: 'paid',
    paidAt: '2026-09-30T17:40:00Z',
    paymentMethod: 'Wire Transfer',
    referenceNumber: 'WT-9923812',
    createdAt: '2026-09-25T00:00:00Z',
  },
  {
    id: 'rent-604',
    leaseId: 'lease-104',
    unitNumber: '3C',
    tenantId: 'user-tenant-4',
    tenantName: 'Robert Langdon',
    amount: 2600,
    period: 'October 2026',
    dueDate: '2026-10-01',
    status: 'overdue',
    referenceNumber: 'INV-RENT-104',
    createdAt: '2026-09-25T00:00:00Z',
  }
];

export const INITIAL_METRICS: ProductivityMetric[] = [
  {
    department: 'leasing',
    avgResolutionHours: 8.5,
    slaComplianceRate: 94.2,
    tasksProcessed: 42,
    activeBottlenecks: 1,
  },
  {
    department: 'maintenance',
    avgResolutionHours: 4.2,
    slaComplianceRate: 98.0,
    tasksProcessed: 68,
    activeBottlenecks: 1,
  },
  {
    department: 'finance',
    avgResolutionHours: 19.4,
    slaComplianceRate: 88.5,
    tasksProcessed: 51,
    activeBottlenecks: 2,
  },
  {
    department: 'legal',
    avgResolutionHours: 26.0,
    slaComplianceRate: 82.0,
    tasksProcessed: 18,
    activeBottlenecks: 2,
  },
  {
    department: 'executive',
    avgResolutionHours: 12.0,
    slaComplianceRate: 91.5,
    tasksProcessed: 14,
    activeBottlenecks: 1,
  }
];

export const INITIAL_COMPLAINTS: TenantComplaint[] = [
  {
    id: 'complaint-101',
    unitNumber: '4B',
    tenantId: 'user-tenant-1',
    tenantName: 'Elena Rostova',
    tenantEmail: 'elena.rostova@example.com',
    category: 'noise_disturbance',
    subject: 'Excessive Bass & Heavy Stomping from Unit 5B after 11 PM',
    description: 'Repeated loud sub-bass vibrations and furniture dragging occurring between 11:30 PM and 2:00 AM on weekdays. This is violating section 4 quiet hours.',
    status: 'under_investigation',
    isConfidential: false,
    priority: 'medium',
    createdAt: '2026-10-01T22:30:00Z',
    updatedAt: '2026-10-02T09:15:00Z',
    responses: [
      {
        id: 'cr-1',
        authorName: 'Ariel Agor',
        authorRole: 'Property Manager',
        message: 'Notice of Quiet Hours covenant has been issued to Unit 5B resident. Courtesy patrol will log noise levels tonight.',
        createdAt: '2026-10-02T09:15:00Z'
      }
    ]
  },
  {
    id: 'complaint-102',
    unitNumber: '2A',
    tenantId: 'user-tenant-2',
    tenantName: 'Marcus Vance',
    tenantEmail: 'marcus.v@example.com',
    category: 'parking_access',
    subject: 'Unauthorized Vehicle Blocking Assigned Space #14',
    description: 'A silver sedan with out-of-state plates has been parked in my reserved subterranean spot for over 36 hours.',
    status: 'action_taken',
    isConfidential: false,
    priority: 'high',
    createdAt: '2026-09-30T18:45:00Z',
    updatedAt: '2026-10-01T08:00:00Z',
    responses: [
      {
        id: 'cr-2',
        authorName: 'Devon Miller',
        authorRole: 'Vendor Coordinator',
        message: 'Towing dispatch warned the vehicle owner. Vehicle removed at 8:15 AM today.',
        createdAt: '2026-10-01T08:00:00Z'
      }
    ]
  },
  {
    id: 'complaint-103',
    unitNumber: '4B',
    tenantId: 'user-tenant-1',
    tenantName: 'Elena Rostova',
    tenantEmail: 'elena.rostova@example.com',
    category: 'cleanliness_trash',
    subject: 'Recycling Chute Jammed on 4th Floor',
    description: 'Cardboard boxes are blocking the recycling access door on 4th floor corridor, causing debris overflow.',
    status: 'submitted',
    isConfidential: false,
    priority: 'low',
    createdAt: '2026-10-02T16:20:00Z',
    updatedAt: '2026-10-02T16:20:00Z',
    responses: []
  }
];

export const INITIAL_TROUBLESHOOTING: TroubleshootingSession[] = [
  {
    id: 'ts-201',
    tenantId: 'user-tenant-1',
    unitNumber: '4B',
    issueDescription: 'Kitchen garbage disposal humming but blades not spinning',
    photoUrls: [],
    status: 'resolved_by_renter',
    createdAt: '2026-09-28T14:10:00Z',
    resolvedAt: '2026-09-28T14:18:00Z',
    result: {
      probableCause: 'Food waste jammed the disposal flywheel causing internal thermal circuit reset',
      canRenterFix: true,
      urgency: 'low',
      recommendedTrade: 'appliance',
      steps: [
        {
          id: 'step-1',
          stepNumber: 1,
          title: 'Power Safety Check',
          instruction: 'Turn off the wall switch and unplug unit under sink before touching anything.',
          spokenInstruction: 'Make sure the disposal wall switch is turned completely off before doing anything else.',
          completed: true
        },
        {
          id: 'step-2',
          stepNumber: 2,
          title: 'Manual Hex Wrench Rotation',
          instruction: 'Insert 1/4 inch Allen key into socket at bottom center of disposal and crank back and forth.',
          spokenInstruction: 'Insert the hex key into the hole underneath the disposal and twist back and forth to free the jam.',
          completed: true
        },
        {
          id: 'step-3',
          stepNumber: 3,
          title: 'Press Red Reset Button',
          instruction: 'Press the red reset button on the bottom of the disposal housing until it clicks.',
          spokenInstruction: 'Now press the little red reset button on the bottom of the disposal until you feel it click.',
          completed: true
        }
      ]
    }
  }
];
