import { getAccessToken } from '../firebase/config';
import { LeaseAgreement, BillItem, MaintenanceRequest, RentPayment } from '../types';

/**
 * Google Drive API Integration
 */
export async function uploadLeaseToDrive(lease: LeaseAgreement): Promise<{ id: string; name: string; webViewLink?: string }> {
  const token = await getAccessToken();
  if (!token) throw new Error("Google Workspace authentication required. Please sign in with Google.");

  const fileContent = `=====================================================
PROPFLOW ENTERPRISE - EXECUTED LEASE AGREEMENT
=====================================================
Property: ${lease.propertyName}
Unit: ${lease.unitNumber}
Tenant: ${lease.tenantName} (${lease.tenantEmail})
Monthly Rent: $${lease.monthlyRent.toLocaleString()}
Security Deposit: $${lease.securityDeposit.toLocaleString()}
Term: ${lease.startDate} to ${lease.endDate}
Status: ${lease.status.toUpperCase()}

ELECTRONIC SIGNATURE AUDIT TRAIL:
Signed By: ${lease.tenantName}
Timestamp: ${lease.signedAt || new Date().toISOString()}
Signature Verification Token: PROPHASH-${lease.id.slice(0, 8)}-VERIFIED
E-Sign Consent: ${lease.termsAccepted ? 'ACCEPTED BY LESSEE' : 'PENDING'}

AGREEMENT TERMS:
${lease.terms.map((t, idx) => `${idx + 1}. ${t}`).join('\n')}

=====================================================
Generated by PropFlow Real Estate Bureaucracy System
=====================================================`;

  const metadata = {
    name: `Lease_${lease.propertyName.replace(/\s+/g, '_')}_Unit_${lease.unitNumber}_${lease.tenantName.replace(/\s+/g, '_')}.txt`,
    mimeType: 'text/plain',
  };

  const form = new FormData();
  form.append('metadata', new Blob([JSON.stringify(metadata)], { type: 'application/json' }));
  form.append('file', new Blob([fileContent], { type: 'text/plain' }));

  const res = await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink', {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}` },
    body: form,
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to upload lease to Google Drive');
  }

  return res.json();
}

export async function uploadBillToDrive(bill: BillItem): Promise<{ id: string; name: string }> {
  const token = await getAccessToken();
  if (!token) throw new Error("Google Workspace authentication required.");

  const fileContent = `BILL & INVOICE VOUCHER
Vendor: ${bill.vendorName}
Invoice #: ${bill.invoiceNumber}
Amount: $${bill.amount.toFixed(2)}
Due Date: ${bill.dueDate}
Category: ${bill.billType}
Status: ${bill.status}
Payment Method: ${bill.paymentMethod || 'Pending'}
Notes: ${bill.notes || 'None'}
Timestamp: ${new Date().toISOString()}`;

  const metadata = {
    name: `Invoice_${bill.vendorName.replace(/\s+/g, '_')}_${bill.invoiceNumber || bill.id.slice(0, 6)}.txt`,
    mimeType: 'text/plain',
  };

  const form = new FormData();
  form.append('metadata', new Blob([JSON.stringify(metadata)], { type: 'application/json' }));
  form.append('file', new Blob([fileContent], { type: 'text/plain' }));

  const res = await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name', {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}` },
    body: form,
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to archive bill to Drive');
  }

  return res.json();
}

/**
 * Google Sheets API Integration
 */
export async function exportRentRollToSheets(payments: RentPayment[]): Promise<{ spreadsheetId: string; url: string }> {
  const token = await getAccessToken();
  if (!token) throw new Error("Google Workspace authentication required.");

  const title = `PropFlow Rent Roll & Billing Ledger - ${new Date().toLocaleDateString('en-US', { month: 'short', year: 'numeric' })}`;
  
  // 1. Create spreadsheet
  const createRes = await fetch('https://sheets.googleapis.com/v4/spreadsheets', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      properties: { title },
      sheets: [
        {
          properties: { title: 'Rent Collection' },
          data: [
            {
              startRow: 0,
              startColumn: 0,
              rowData: [
                {
                  values: [
                    { userEnteredValue: { stringValue: 'Unit' } },
                    { userEnteredValue: { stringValue: 'Tenant' } },
                    { userEnteredValue: { stringValue: 'Period' } },
                    { userEnteredValue: { stringValue: 'Amount ($)' } },
                    { userEnteredValue: { stringValue: 'Due Date' } },
                    { userEnteredValue: { stringValue: 'Status' } },
                    { userEnteredValue: { stringValue: 'Payment Method' } },
                    { userEnteredValue: { stringValue: 'Ref Number' } },
                  ]
                },
                ...payments.map(p => ({
                  values: [
                    { userEnteredValue: { stringValue: p.unitNumber } },
                    { userEnteredValue: { stringValue: p.tenantName } },
                    { userEnteredValue: { stringValue: p.period } },
                    { userEnteredValue: { numberValue: p.amount } },
                    { userEnteredValue: { stringValue: p.dueDate } },
                    { userEnteredValue: { stringValue: p.status.toUpperCase() } },
                    { userEnteredValue: { stringValue: p.paymentMethod || 'N/A' } },
                    { userEnteredValue: { stringValue: p.referenceNumber || 'N/A' } },
                  ]
                }))
              ]
            }
          ]
        }
      ]
    })
  });

  if (!createRes.ok) {
    const err = await createRes.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to create Google Sheet');
  }

  const data = await createRes.json();
  return {
    spreadsheetId: data.spreadsheetId,
    url: `https://docs.google.com/spreadsheets/d/${data.spreadsheetId}/edit`,
  };
}

/**
 * Google Calendar API Integration
 */
export async function scheduleMaintenanceInCalendar(
  request: MaintenanceRequest,
  startTimeIso: string
): Promise<{ id: string; htmlLink: string }> {
  const token = await getAccessToken();
  if (!token) throw new Error("Google Workspace authentication required.");

  const start = new Date(startTimeIso);
  const end = new Date(start.getTime() + 2 * 60 * 60 * 1000); // 2 hours duration

  const event = {
    summary: `[PropFlow Maintenance] ${request.title} - Unit ${request.unitNumber}`,
    description: `Category: ${request.category.toUpperCase()}\nPriority: ${request.priority.toUpperCase()}\nLessee: ${request.lesseeName} (${request.lesseeEmail})\n\nIssue Details: ${request.description}\n\nAssigned Vendor: ${request.assignedVendor || 'Pending Dispatch'}\nVendor Contact: ${request.vendorContact || 'N/A'}`,
    location: `${request.propertyName}, Unit ${request.unitNumber}`,
    start: { dateTime: start.toISOString() },
    end: { dateTime: end.toISOString() },
    reminders: {
      useDefault: false,
      overrides: [
        { method: 'email', minutes: 24 * 60 },
        { method: 'popup', minutes: 30 },
      ]
    }
  };

  const res = await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(event),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to schedule event in Google Calendar');
  }

  return res.json();
}

/**
 * Gmail API Integration
 */
export async function sendEmailViaGmail(
  to: string,
  subject: string,
  bodyContent: string
): Promise<{ id: string }> {
  const token = await getAccessToken();
  if (!token) throw new Error("Google Workspace authentication required.");

  const emailLines = [
    `To: ${to}`,
    `Subject: ${subject}`,
    'Content-Type: text/plain; charset=utf-8',
    'MIME-Version: 1.0',
    '',
    bodyContent,
  ];

  const rawMessage = emailLines.join('\r\n');
  const base64Encoded = btoa(unescape(encodeURIComponent(rawMessage)))
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');

  const res = await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ raw: base64Encoded }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to dispatch email via Gmail');
  }

  return res.json();
}

/**
 * Google Tasks API Integration
 */
export async function createGoogleTask(
  title: string,
  notes: string,
  dueDateIso?: string
): Promise<{ id: string; title: string }> {
  const token = await getAccessToken();
  if (!token) throw new Error("Google Workspace authentication required.");

  const taskPayload: any = {
    title,
    notes,
  };
  if (dueDateIso) {
    taskPayload.due = new Date(dueDateIso).toISOString();
  }

  const res = await fetch('https://tasks.googleapis.com/tasks/v1/lists/@default/tasks', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(taskPayload),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to create task in Google Tasks');
  }

  return res.json();
}

/**
 * Google Contacts (People API)
 */
export async function syncTenantContact(
  givenName: string,
  familyName: string,
  email: string,
  phone?: string
): Promise<{ resourceName: string }> {
  const token = await getAccessToken();
  if (!token) throw new Error("Google Workspace authentication required.");

  const contactData: any = {
    names: [{ givenName, familyName }],
    emailAddresses: [{ value: email, type: 'work' }],
  };

  if (phone) {
    contactData.phoneNumbers = [{ value: phone, type: 'mobile' }];
  }

  const res = await fetch('https://people.googleapis.com/v1/people:createContact', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(contactData),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to sync contact with Google Contacts');
  }

  return res.json();
}
